# Generated by Django 4.2.3 on 2023-07-28 17:16

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('event_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536),
            preserve_default=False,
        ),
    ]
